### PR TITLE
Add option to check soft deleted models for uniqueness

### PR DESCRIPTION
**Pull request by marcusmoore**
This is an attempt to address #12. I apologize if this isn't what the author intended but I think I understood correctly.

I'm not sure about the naming and I'm open to feedback.

I just realized for forgot to update the readme. Let me know if you intend to pull this in and I'll update it.

### CODE REVIEW

**Comment by freekmurze** [comment]
This PR fails on Laravel 5.1

https://travis-ci.org/spatie/laravel-sluggable/jobs/168503651#L368

Could you fix that error?

**Comment by marcusmoore** [comment]
I wasn't able to figure it out yet. It looks like the issue is with Laravel 5.2's SoftDeletes. I'll work on it again tonight. Feel free to throw any pointers my way.

**Comment by marcusmoore** [comment]
Actually, I just looked at your comment again @freekmurze, I'm not sure but looking at the raw log from travis [here](https://s3.amazonaws.com/archive.travis-ci.org/jobs/168503651/log.txt) isn't it installing 5.2? If I remember correctly, 5.2 is what was installed on my machine when I ran `composer update --prefer-lowest`.

Does that sound right?

**Comment by freekmurze** [comment]
You're right, it's in Laravel 5.2 that this PR fails

**Comment by freekmurze** [comment]
Hi, because in our projects we're probably never going to use soft deletes, I've decided to not merge this in.

**Pull request closed without merging**
