### PR TITLE
Fixes $slugOptions variable

### PR DESCRIPTION
**Pull request by dhi2**
Resulted in error as seen here: https://github.com/rinvex/laravel-categories/issues/70

### CODE REVIEW

**Comment by freekmurze** [comment]
I think we should make the typehint nullable instead of filling it with a string.

**Comment by freekmurze** [comment]
Closing due to inactivity.

**Comment by dhi2** [comment]
> Closing due to inactivity.

@freekmurze Why is this closed due to inactivity? What kind of activity were you expecting? Please merge this, it's breaking our app.

**Comment by freekmurze** [comment]
I think the typehint should be made nullable instead of filling it with a string. Please make that adjustment and let me know if that work in your app.

**Comment by dhi2** [comment]
@freekmurze Not sure what that means, that all sounds chinese to me. Can you do it if you know how?

**Pull request closed without merging**
